export const DIR_RTL = 'rtl'
export const DIR_LTR = 'ltr'
export const MODE_LIGHT = 'light'
export const MODE_DARK = 'dark'
export const MODE_SYSTEM = 'system'

export const SIDE_NAV_WIDTH = 240
export const SIDE_NAV_COLLAPSED_WIDTH = 60
export const SIDE_NAV_FOOTER_HEIGHT = 68
export const SPLITTED_SIDE_NAV_MINI_WIDTH = 68
export const STACKED_SIDE_NAV_SECONDARY_WIDTH = 270
export const SIDE_NAV_CONTENT_GUTTER = 8
export const LOGO_X_GUTTER = 16
export const HEADER_HEIGHT = 64
export const HEADER_EXTENDED_HEIGHT = 56
export const PAGE_CONTAINER_GUTTER_X = 'px-4 sm:px-6 md:px-8'
export const PAGE_CONTAINER_GUTTER_Y = 'py-4 sm:py-6 md:px-8'

export const LAYOUT_INSET_SHELL = 'insetShell'
export const LAYOUT_STACKED_SIDE = 'stackedSide'
export const LAYOUT_TOP_BAR_CLASSIC = 'topBarClassic'
export const LAYOUT_SEAMLESS_SIDE = 'seamLessSide'
export const LAYOUT_DUO_TIER_HEADER = 'duoTierHeader'
export const LAYOUT_BLANK = 'blank'

export const THEME_ENUM = {
    DIR_RTL: DIR_RTL,
    DIR_LTR: DIR_LTR,
    MODE_LIGHT: MODE_LIGHT,
    MODE_DARK: MODE_DARK,
    MODE_SYSTEM: MODE_SYSTEM,
    SIDE_NAV_WIDTH: SIDE_NAV_WIDTH,
    SIDE_NAV_COLLAPSED_WIDTH: SIDE_NAV_COLLAPSED_WIDTH,
    SPLITTED_SIDE_NAV_MINI_WIDTH: SPLITTED_SIDE_NAV_MINI_WIDTH,
    STACKED_SIDE_NAV_SECONDARY_WIDTH: STACKED_SIDE_NAV_SECONDARY_WIDTH,
    HEADER_HEIGHT: HEADER_HEIGHT,
    LAYOUT_INSET_SHELL: LAYOUT_INSET_SHELL,
    LAYOUT_STACKED_SIDE: LAYOUT_STACKED_SIDE,
    LAYOUT_TOP_BAR_CLASSIC: LAYOUT_TOP_BAR_CLASSIC,
    LAYOUT_SEAMLESS_SIDE: LAYOUT_SEAMLESS_SIDE,
    LAYOUT_DUO_TIER_HEADER: LAYOUT_DUO_TIER_HEADER,
} as const
