'use client'

import Alert from '@/components/ui/Alert'
import Skeleton from '@/components/ui/Skeleton'
import Button from '@/components/ui/Button'
import Collapsible from '@/components/ui/Collapsible'
import Scroll from '@/components/ui/Scroll'
import GalleryImage from './GalleryImage'
import GeneratorPrompt from './GeneratorPrompt'
import ImageLandingView from './ImageLandingView'
import SettingPanelContent from './SettingPanelContent'
import ToggleDrawer from '@/components/shared/ToggleDrawer'
import { LuChevronDown, LuChevronUp, LuDownload } from 'react-icons/lu'
import { useAiImageStore } from '../_store/aiImageStore'
import classNames from '@/utils/classNames'

const PreviewZone = () => {
    const { isGeneratingImage, generatedImage } = useAiImageStore()

    const buttonClass =
        'hover:bg-gray-200/60 dark:hover:bg-gray-700 text-gray-900 dark:text-gray-100'

    return (
        <div className="flex-1 h-full p-4 container mx-auto">
            <div className="flex flex-col justify-between h-[calc(100%-30px)]">
                <div className="lg:hidden">
                    <ToggleDrawer
                        bodyClass="p-0"
                        closable={false}
                        placement="left"
                    >
                        <SettingPanelContent />
                    </ToggleDrawer>
                </div>
                <div className="relative h-[calc(100%-100px)] lg:h-[calc(100%-80px)] xl:lg:h-full">
                    <div className="absolute top-0 left-0 h-full w-full py-4">
                        {generatedImage.length === 0 && !isGeneratingImage && (
                            <ImageLandingView />
                        )}
                        <Scroll
                            className={classNames(
                                'overflow-y-auto max-w-full',
                                generatedImage.length > 0 && 'h-full',
                            )}
                        >
                            {generatedImage.length > 0 && (
                                <Alert showIcon className="mb-4" type="info">
                                    This is a mock response designed to simulate
                                    an AI-generated reply. Please note that
                                    these image is not generated by an actual AI
                                    model.
                                </Alert>
                            )}
                            {isGeneratingImage && (
                                <div className="rounded-lg bg-gray-50 dark:bg-gray-700 p-4 mb-4">
                                    <div className="grid grid-cols-2 xl:grid-cols-4 gap-4">
                                        {[...Array(4).keys()].map((item) => (
                                            <Skeleton
                                                key={`loading-${item}`}
                                                className="rounded-xl bg-gray-300 dark:bg-gray-600 h-[340px] lg:h-[150px] xl:h-[340px]"
                                            />
                                        ))}
                                    </div>
                                </div>
                            )}
                            {generatedImage.length > 0 &&
                                generatedImage.map((item) => (
                                    <Collapsible
                                        className="rounded-lg bg-gray-50 dark:bg-gray-800 p-4 mb-4"
                                        defaultOpen={true}
                                        key={item.prompt + item.id}
                                    >
                                        <div className="flex items-center justify-between gap-2">
                                            <h6 className="font-medium heading-text">
                                                {item.prompt}
                                            </h6>
                                            <div className="flex items-center">
                                                <Button
                                                    size="sm"
                                                    variant="subtle"
                                                    className={() =>
                                                        buttonClass
                                                    }
                                                    icon={<LuDownload />}
                                                >
                                                    Download all
                                                </Button>
                                                <Collapsible.Trigger>
                                                    {({ isOpen, toggle }) => (
                                                        <Button
                                                            variant="ghost"
                                                            size="sm"
                                                            onClick={toggle}
                                                            className={() =>
                                                                buttonClass
                                                            }
                                                            icon={
                                                                isOpen ? (
                                                                    <LuChevronDown />
                                                                ) : (
                                                                    <LuChevronUp />
                                                                )
                                                            }
                                                        />
                                                    )}
                                                </Collapsible.Trigger>
                                            </div>
                                        </div>
                                        <Collapsible.Content className="mt-2">
                                            <div className="grid grid-cols-2 xl:grid-cols-4 gap-4 p-1">
                                                {item.gallery.map((gallery) => {
                                                    return (
                                                        <GalleryImage
                                                            key={gallery.id}
                                                            galleryItem={
                                                                gallery
                                                            }
                                                        />
                                                    )
                                                })}
                                            </div>
                                        </Collapsible.Content>
                                    </Collapsible>
                                ))}
                        </Scroll>
                    </div>
                </div>
                <GeneratorPrompt />
            </div>
        </div>
    )
}

export default PreviewZone
